### ISSUE TITLE
Block Gate doesnt update the circle location correctly.

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#10]
Placed down the block gate, right clicked to select an area and that area works, but then afterwards any further ones arent shown until the block gate gets a block update, but these arent correct anyways, relogging will bring it back to the position it was in before that worked.

*side note: Block gate works fine with using items like hoes and using durability and works fine placing items like seeds.

**Comment by hilburn** [comment]
Yeah... for some reason VSWE spams the packet data incessantly so I just disabled it for now - I will fix it (probably tomorrow)

**Comment by hilburn** [comment]
fixed
