### ISSUE TITLE
Alpha 2 Issue

### ISSUE THREAD

**Issue by Shotch** [hilburn/AdvancedSystemsManager#11]
Placing a system manager causes immediate crash

http://pastebin.com/9tUhbayW

**Comment by hilburn** [comment]
ok, do you have the full forge log for that one - because something really weird is happening

**Comment by Shotch** [comment]
...Would that be "fml-client-[number here]"? Just asking to be certain that you get the correct information

**Comment by hilburn** [comment]
yeah those are the ones - basically the full console log

**Comment by Shotch** [comment]
It's too larger for Pastebin, so I'll leave this here, hope it works out. https://drive.google.com/file/d/0B-pwbwsnV9oET191cWlNNTRBLXM/view?usp=sharing

**Comment by hilburn** [comment]
Ah thanks, I gave myself an accidental NEI dependency

**Comment by Rapthera** [comment]
@SHotch Just for the future, paste.ubuntu.com has a much higher max file size, so you can use that instead of pastebin when file sizes are too large ;)

**Comment by hilburn** [comment]
Should be fixed in 0.1.2
