### ISSUE TITLE
Bug : Crash when placing the machine inventory manager

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#12]
Completely stock forge 1291 Environment with only This mod installed.

http://pastebin.com/Lyic9DZt

If i try to re-open the saved game then i crash with this error:

http://pastebin.com/GGJXUf86

**Comment by hilburn** [comment]
yeah - I accidentally gave the gui an NEI dependency, download 0.1.2 and it should be fixed
