### ISSUE TITLE
Bug: Specify item amount

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#13]
When you press specify item amount the same will kick you out and say "a fatal error has occured, This connection is terminated"

Can't get a error log. Sorry.

**Comment by hilburn** [comment]
Anything in the console?

**Comment by ghost** [comment]
Not able to get the console up sorry. Using a default minecraft.exe with forge. I will see what i can do though :)

**Comment by ghost** [comment]
here you go :) 
http://pastebin.com/GnXdRMn1

**Comment by Zhab80** [comment]
I think you might need to post a "how to get log" guide or link to one. The amount of time people tell you "no log" is huge.

**Comment by hilburn** [comment]
thanks - i found the issue

**Comment by ghost** [comment]
:)

**Comment by Rodg88** [comment]
Just tested with 0.1.3, and I could check the specify amount box, but got this error when I UNchecked it http://pastebin.com/3WFQRyW8

**Comment by hilburn** [comment]
the less said about that derp the better. a fixed version will go out tomorrow
