### ISSUE TITLE
(minor) option to open/close command with just arrow or whole box doesn't also toggle command movement selection

### ISSUE THREAD

**Issue by Rodg88** [hilburn/AdvancedSystemsManager#16]
When you uncheck the preference "Clicking on the top part of a command (or the full small command) will open or close it." it doesn't let you click and drag the command around by clicking on the top part of the command, just the small box in the top left as usual. In SFM I believe when this preference was unchecked, you could move commands by clicking anywhere in the top part other than the arrow to open/close the command.

PS Sorry for the long title lol

**Comment by hilburn** [comment]
Nope - in SFM you could only ever use the top right corner - but this is a nice idea so I will implement it

**Comment by hilburn** [comment]
Added
