### ISSUE TITLE
Error connecting outputs to more commands and crash

### ISSUE THREAD

**Issue by Rodg88** [hilburn/AdvancedSystemsManager#18]
I was testing simple furnace automation, with: trigger - input all coal and cobble - output coal to furnace fuel slot - output cobble to furnace top slot. I'd made and connected the first 3 commands (up to fuel output), and had made a command for outputting the cobble, but when I clicked on the output fuel's command's output tab to connect to the cobblestone command, I got this error: http://pastebin.com/rz4NvRJS (MC didn't crash, just closed the world)
When I re-opened the world and tried again, it worked with no error.

The same thing happened again connecting the cobblestone output to a new input.

Then once I'd also added in commands to extract the smoothstone, I check the output of the furnace and see it isn't extracting the smoothstone like it should have been, go back to check the manager, right click the manager and crash before the GUI opens: http://pastebin.com/25pwx00U

**Comment by hilburn** [comment]
Should be fixed - though i recommend breaking and replacing your manager (once i've released the new version)
