### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by Rodg88** [hilburn/AdvancedSystemsManager#19]
In 0.1.3, I set up 2 chests, and a trigger/input/output setup. I put coal and cobble in one chest, and blacklist coal on the input command, or the output, or both, and it still moves the coal. Whitelisting works normally.

**Comment by hilburn** [comment]
should be fixed in 0.1.4 - lemme know

**Comment by Shotch** [comment]
It is working properly for me on 0.1.4
