### ISSUE TITLE
Suggestion: For variables.

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#21]
Hay, Just a suggestion but for variables would it be possible to be able to use either colors or names. I think this would allow for much more complex builds. 

Ps: Loving the reworked systems and the modified textures are lovely. Great work so far : )

**Comment by hilburn** [comment]
I am considering making them able to take hex values which will give you (nearly) unlimited variables - and you can name them by naming the Command they are set in

**Comment by ghost** [comment]
Okay sounds good. 
Will you be adding command groups?

**Comment by hilburn** [comment]
yeah - everything that is in SFM will be in ASM eventually
Maybe not in the same form exactly, but probably better

**Comment by ghost** [comment]
Awesome. I can not wait. Also i would love just a generic if not statement. It would make things simpler.

**Comment by hilburn** [comment]
I could add a _not_ checkbox to normal conditions pretty easily, which would flip the output - is that what you were thinking of?

**Comment by ghost** [comment]
Yeah sounds great. I find not logic something that can be very useful

**Comment by ghost** [comment]
Hmm, Would a change log be out of the question so we can see whats going on with whats being added / removed / fixed?

**Comment by hilburn** [comment]
There will be when I get out of these initial alphas.
