### ISSUE TITLE
Layering

### ISSUE THREAD

**Issue by Shotch** [hilburn/AdvancedSystemsManager#23]
If you open up multiple commands at once and set a blacklist or whitelist that happens to include a block, the commands layer partially through the blocks.

I think this screenshot explains it a bit better than I can through text. http://i.imgur.com/Gf0Jspr.png

**Comment by hilburn** [comment]
Yeah - I need to do some wok on the gui stuff, it's on the list

**Comment by hilburn** [comment]
Ok - fixed
