### ISSUE TITLE
0.1.6 Redstone Emitter

### ISSUE THREAD

**Issue by Shotch** [hilburn/AdvancedSystemsManager#25]
Redstone emitters aren't saved once you set them and leave the gui. You can set it, but on gui close, it unsets it.

**Comment by hilburn** [comment]
Ok.. this one I am not sure about - because it works fine on my build - persisting through gui closing and opening and world reloads. I wouldn't have released it if it wasn't at least working on the surface.

Do you get any warnings in the console when messing with them?

**Comment by Shotch** [comment]
..I forgot to place a new manager after updating, the issue resolved itself after I replaced the manager and tried again. Sorry

**Comment by hilburn** [comment]
That's really weird... it shouldn't make a difference - new commands should be backwards compatible (and have been in dev). I'll look into that as a separate issue if it crops up again when I add in some more new ones later today and over the weekend
