### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#26]
http://gyazo.com/534141c4461776af7424986e5dcaafc7

This happens on all item search's.

**Comment by hilburn** [comment]
When you say "all item search's" do you mean all of them in Camouflage menu?

**Comment by ghost** [comment]
Na. I mean if you want to pick a item to filter or to be white listed etc. When you get it to only show one line of items you are still able to scroll it and it looks really odd.

**Comment by hilburn** [comment]
Ok, fixed

**Comment by ghost** [comment]
Awesome :)
