### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#27]
Just a suggestion but would you be able to make it so when you craft one of the specific blocks you can then craft it again with system cable so it acts as both so you have the option to not need extra cable to connect things like item detectors that are next to each other.

**Comment by Shotch** [comment]
What you are looking for exists, they are called Cable Clusters. You craft them with the blocks you want, and then they take on the properties of the ones you craft hem with.

**Comment by ghost** [comment]
Oh, Okay. Sorry. never played with them before :).

**Comment by Zhab80** [comment]
Also existed in the original mod (SFM).
