### ISSUE TITLE
Suggestion: inventory checks

### ISSUE THREAD

**Issue by ghost** [hilburn/AdvancedSystemsManager#28]
Hay ya, I tired to explain this before and failed at it but after needing to do this again I have managed to come up with a easy way to say it. 

I need a way to say to the system. If selected inventory is full then stop. if selected inventory is empty then go. This is something that can not be done with out telling the system manager what items can fill it.

Edit: 
A way to say if items are in inventory x then move matching items in inventory y to inventory z. That may be confusing but it would be like having a variable but the variable is the chest and the items is the content of the variable. 

Hope that makes sense.

**Comment by hilburn** [comment]
There is no sensible way to do this currently. And frankly I don't see much use for it, the cases where you want to move items matching X's inventory from Y to Z is so limited I can't actually think of any situations I'd want to do it.
I may look into it in the future but it definitely won't be in the initial release.

**Comment by ghost** [comment]
What about the "if inventory full/empty thing"?

**Comment by hilburn** [comment]
Empty is easy to do - just have a condition with the item set to Match: Any and then False gives you empty.

**Comment by ghost** [comment]
Oh yeah. Wow. I feel stupid. Thanks. What about full though?

**Comment by hilburn** [comment]
You can't. I'll think about it

**Comment by Zhab80** [comment]
You can use a vanilla comparator to get a redstone signal that is weaker or stronger according to how full the inventory is. Then you feed that signal to a redstone receiver. Many mod blocks also interact with a comparator. Other ones do not.

With a little help from buildcraft gates action, you can get a signal from a whole bunch of conditions involving just about any block there is. Other mods can also achieve similar results.

**Comment by hilburn** [comment]
Well yes this is all doable - my point was that you can't do it purely in ASM (at least currently)
My plan is to integrate Comparators with a "Comparator Condition" which will handle a bunch of these scenarios as a combined comparator+receiver+redstone condition

**Comment by Zhab80** [comment]
Well ok then. It seems like you are doing quite a bit more than just "thinking about it".

**Comment by hilburn** [comment]
I had 2 whole hours to think about it before you posted :P

**Comment by bladedpenguin** [comment]
If I understand correctly, you are suggesting some kind of latch? Put Inventory Y in a variable and push from variable Y to inventory Z. Separately, check inventory X with a condition or comparator. If X is full, set Var Y to nothing. When X is empty again, set Var Y to Inv Y. This way, Z will be fed until X is full, then Z will stop getting fed until X is empty again.
