### ISSUE TITLE
Other things

### ISSUE THREAD

**Issue by hilburn** [hilburn/AdvancedSystemsManager#43]
- [ ] Gui Rewrite (please don't ask about this - it's going to be big and hard to explain)
- [ ] Right click dropdown menu - with conext dependent functionality.
- [ ] Labeller - sort that shit out, the gui and implementation is messy as hell
- [x] be less busy at work

**Comment by ghost** [comment]
Hows it all going? pre-alpha soon?

**Comment by hilburn** [comment]
alpha this week if all goes to plan

**Comment by ghost** [comment]
Awesome :)
