### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by hilburn** [hilburn/AdvancedSystemsManager#48]
This will happen soon (within 24hrs) last chance for @way2muchnoise to raise any issues

**Comment by Shotch** [comment]
\o/ hype for more testing

**Comment by way2muchnoise** [comment]
_cracks knuckles_ Let's do this

**Comment by Haggle1996** [comment]
Will the alpha release be in-place compatible with SFM? Or will my players need to redo all SFM machinery?

**Comment by ghost** [comment]
I dont believe any version will be in-place compatible with SFM. They are separate mods, your players will need to redo their machines and code. AFAIK.

**Comment by Haggle1996** [comment]
Would be nice if there was a utility to save an SFM script and reload it in ASM, but completely understand the time and difficulties. Excited for the alpha release!

**Comment by ghost** [comment]
@Haggle1996 I think he is going to work on something but not until the end.

**Comment by hilburn** [comment]
@Haggle1996 - there are a number of problems with the compatibility between the two. I will see what I can do before it goes into a proper (beta) release though

**Comment by hilburn** [comment]
Oh and to everyone involved in this conversation - taking suggestions for recipes for the Fluid Gate because I suck at them

**Comment by ghost** [comment]
Same as the block gate but with an empty bucket instead of a pickaxe?

**Comment by hilburn** [comment]
Yeah that was pretty much what I was thinking
