### ISSUE TITLE
RFNode doesn't update textures and connections on target adjust

### ISSUE THREAD

**Issue by way2muchnoise** [hilburn/AdvancedSystemsManager#49]
The blocks doesn't update when a new direction is selected. Ducts won't connect for this reason.

![](http://puu.sh/joPuj/6f675ea8f6.png)![](http://puu.sh/joPvH/1fcdd3bd74.jpg)

Reloading the world fix it but Ducts still won't connect (they will work but the client doesn't show them connected)

**Comment by way2muchnoise** [comment]
@hilburn since 9c1dc1759191b62eec14d7fe6270e906c56fb534 they update but don't update on deletion of the flow component

**Comment by ghost** [comment]
http://pastebin.com/7LmuyPVv - Crash on messing with the settings in the command.

Hilburn - "hilburn> post an issue or comment on the closed on of way's
<hilburn> so i remember"
