### ISSUE TITLE
Crash with Remote Interface

### ISSUE THREAD

**Issue by Shotch** [hilburn/AdvancedSystemsManager#5]
Simply just right clicked on a Machine Inventory Manager while holding Remote Interface bound the the Inventory manager.

EDIT: Also happens with Advanced Remote Interface, I was shifting while right clicking, and then I unshifted while holding right click, Gui opens and it crashes.

http://pastebin.com/KcEMaHNm

**Comment by Zhab80** [comment]
Is this mod out or something ? If yes, where ?

Edit: nevermind. found it.

**Comment by hilburn** [comment]
interesting - i'll look into it. Thanks for giving it a test at least

**Comment by hilburn** [comment]
Should be fixed in 0.1.2
