### ISSUE TITLE
Server side crash because of client code.

### ISSUE THREAD

**Issue by mindcloud69** [hilburn/AdvancedSystemsManager#56]
see gist [here](https://gist.githubusercontent.com/mindcloud69/0d0ed38111e786411113/raw/50c0274d4f0cd53e8bac5ef19526707343e95940/gistfile1.txt)

**Comment by ghost** [comment]
Jesus that hurt my eyes.
For @hilburn here is the error with out the rest of the log if you want it. 
http://pastebin.com/ZG97L4sE

**Comment by mindcloud69** [comment]
LOL sorry. I'd rather provide to much than to little.
