### ISSUE TITLE
Out of bounds exception, when trying to link up a for/each loop, also no "Current" variable selection.

### ISSUE THREAD

**Issue by AlphaSparqy** [hilburn/AdvancedSystemsManager#58]
http://pastebin.com/BTEc1sgr

Index out of bounds exception on AdvancedSystemsManager-1.7.10-0.1.9.jar
when trying to link up a for/each loop to a group

Also, where does one select the variable to be the "current object" of a loop in this new GUI?

**Comment by hilburn** [comment]
You just click it, the background will be highlighted blue, just like selecting any machine in any of the other lists

**Comment by AlphaSparqy** [comment]
I'm sorry, in the old SFM, there were 2 variables selected for the for/each loops.  The List, and the place holder for the "Each", that was referenced from commands within the loop.

Am I able to select both, within this one list?  How do I differentiate which is for which purpose?

**Comment by hilburn** [comment]
You don't, you simply select the list and it loops through that list
