### ISSUE TITLE
Various GUI problems 0.1.9

### ISSUE THREAD

**Issue by AlphaSparqy** [hilburn/AdvancedSystemsManager#59]
The small hit boxes on the title area of each command are non-visible for me.
Ie.  The tiny box in the upper left of the title area, for moving the command.
The button to re-name it, and the buttons to confirm/cancel the renaming are not visible.
The font is overly large, and if the preference is selected to always show command type, they overlap each other.
When selecting the type for a variable, the bottom rows seem to be a few options all overlapping each other, with no way to scroll down the list.

**Comment by hilburn** [comment]
Gui Issues like this are not going to be solved - the entire GUI is getting rewritten and none of the above will be applicable

**Comment by AlphaSparqy** [comment]
Oh! ok, I had thought this WAS the new GUI.

**Comment by hilburn** [comment]
Ah no, it was going to be, then I decided it wasn't ambitious or flexible enough for what I wanted to do so am basically scrapping all of it
