### ISSUE TITLE
Crash on 0.1.10

### ISSUE THREAD

**Issue by LuxusDarkangel** [hilburn/AdvancedSystemsManager#63]
You need to use ASM 0.1.10 alongside with waila, or it will crash on startup (no, disabling the tags option on the cfg don't solve this crash)
I don't think crash report is needed, but anyway there you go: http://pastebin.com/mqpT3qHg

**Comment by hilburn** [comment]
Why aren't you using WAILA? werido :p 

I'll get this fixed ASAP
