### ISSUE TITLE
Server kick when right clicking Systems Manager

### ISSUE THREAD

**Issue by LuxusDarkangel** [hilburn/AdvancedSystemsManager#65]
This bug has been already reported in curseforge, but for more visibility and since there isn't any type of log, i'll repost it here. Sorry if that's a problem for you.
As title say, right clicking Systems Manager kicks you from server showing the message: Connection Lost Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: The received string length is longer than maximum allowed (22 > 20)
Here is the client error log: http://pastebin.com/1AKRnhdb
Of course i'm using 0.1.10.

**Comment by hilburn** [comment]
Ok this is very strange - are you playing on a server?

**Comment by LuxusDarkangel** [comment]
Yes.

**Comment by hilburn** [comment]
Should be fixed
