### ISSUE TITLE
Inputting and Outputting from Rotarycraft Machines.

### ISSUE THREAD

**Issue by bpwhelan** [hilburn/AdvancedSystemsManager#66]
I was trying to make a simple input output program with a grinder, and ore gets put into all different slots on the grinder (input, lubricant bucket, and output even), as well as it pulls from any slot (ie, puts the ore being processed straight into my furnace). There could be/probably is other issues with different RoC machines, but so far only experimented with the grinder.

**Comment by bpwhelan** [comment]
Hello, Thank you for the quick fix, but it was only a partial fix unfortunately, when i try to output from the grinder into the furnace, it still pulls from the input slot.

**Comment by hilburn** [comment]
Ah ok - I misunderstood the problem, something to do with addressing it at 4.30am when i woke up and couldn't get back to sleep.

It's actually fixed now, and will be included in the next release

**Comment by bpwhelan** [comment]
Thanks! :D Keep up the great work, it's unfortunate that VSWE went MIA all of a sudden, but I'm really excited to see where you take it.
