### ISSUE TITLE
What the hell is going on with my items bug

### ISSUE THREAD

**Issue by LuxusDarkangel** [hilburn/AdvancedSystemsManager#69]
This is a bug with AE2 charger. I setted up a trigger which takes certus quartz from one chest, and puts it on the charger. Then, the same trigger, in other side, tries to take charged certus quartz from the charger to put it on the chest. The problem here is that it puts one certus quartz on te charger, and then... well... all the other certus quartz disappear after some strange things happening to the stack.

**Comment by hilburn** [comment]
Ok, screenshots? How is it disappearing? All at once or a couple at a time?

**Comment by LuxusDarkangel** [comment]
I uploaded a video, because it's very hard to explain...
https://www.youtube.com/watch?v=cnfx81ODbQk
PD: I noticed i'm using GregTech certus quartz because the mod replaces it. Still i don't think that's the problem.

**Comment by hilburn** [comment]
Hmmm ok, I'll have a look at this, very strange

**Comment by Mithos21** [comment]
I also am having this issue while using ASM to automate the production of AE2 Processors, using DW20's code - found here https://youtu.be/8ZS4SzD7s4U?t=22m49s.

The SFM code carries into ASM fine until I put in the last part for final assembly of the circuit, silicon, and redstone. After the final assembly group is put in, When I try to use any of the earlier parts of the commands, say, put pure certus in to make a calculation circuit, the manager pulls other items into itself (such as the Inscriber Engineering Press), but doesn't output them anywhere. This issue does not occur when written in an SFM manager. 

Edit: Retesting in a creative world to rewrite the commands, was able to duplicate the issue.

**Comment by hilburn** [comment]
Ok so I've found the issue. I am not sure why it's occuring but I've found a workaround.
