### ISSUE TITLE
[Enhancement|Issue(?)] Block Gate Placing | Network Package

### ISSUE THREAD

**Issue by accessdenied0** [hilburn/AdvancedSystemsManager#70]
Dear @hilburn,

I got something to mention about the **Block Gate** because like in the original there is this strange issue or something that it place the Block one "above" the original place. But if I use a condition to check if there is some specific block it works as intended: It just check the Block directly "above" the **Block Gate**, but it doesn't prevent the issue. It do not place another block "above" if I mine the extra block, but It do it again if there isn't any block.
I hope this is be fixable... it would be pretty awesome.

Anyway... as I used the **Block Gate** with a Chest (in SSP) with some cobblestone in it. I tried to avoid this "placing bug" with using the "using slots" on the **Block Gate** (0|0) i got some issues. (Maybe the Profiling of Mystcraft can be also an issue) http://pastebin.com/Tc82cQP7
I was able to re-log and remove the Gate but I got this issue 2-3 times until I was able to remove it.

I hope you can help,

access_denied

**Comment by hilburn** [comment]
I'll have a look at the network bug issue, see if I can recreate it. The usability changes might happen, but I'm afraid they're not a priority currently

You can "fix" this if you shift+click on the face the block gate is clicking from - but I know this isn't an ideal solution

**Comment by hilburn** [comment]
Block placing has been fixed - been unable to repeat the network bug but i'll give it another go
