### ISSUE TITLE
Multiple issues with latest version

### ISSUE THREAD

**Issue by mrammy** [hilburn/AdvancedSystemsManager#75]
Localization asm.gui.RfStorage
Clipping on dropdown of container types menu ![](http://i.imgur.com/1gWQKJl.png)
Localization asm.gui.ConnectionDelayOutput ![](http://i.imgur.com/EQWuFjs.png)
more clipping on container types ![](http://i.imgur.com/RtvFN9q.png)
issue with container variables. 
World save (requires AE): http://www.mediafire.com/download/f2r1rk4b0c74193/WorldSave.7z
Ran it into your dev environment with AE2 rv2 stable-10 dev added to the libs directory
Super crappy recording: https://www.mediafire.com/?md1d1pe1d9ci2po

Steps to replicate container issue.
1. Add all chargers to variable (White is used in this case)
2. Run crafting sequence in AE for charged certus quartz crystals.
3. Watch certus only go into the last charger.
4. Check manager GUI
5. Notice at the end of the list only one charger is selected.

Expected for loop to distribute to all chargers instead it picks one and the list empties.
List contains 20 members and only empties after the for loop runs.

If I was a markdown god I would make this pretty but sadly I'm not

sorry,
mrammy

Recipes:
Void Container (shapeless) [ system cable, magma cream, blaze rod ]
Remote Interface (shaped) ![](http://i.imgur.com/gnXAQLp.png) or ![](http://i.imgur.com/Utc63WV.png)
Advanced Remote Interface (shapeless) [ remote interface, beacon ]

**Comment by hilburn** [comment]
Menu clipping I'm not particularly interested in due to the whole massive gui rewrite, but I'll look into the rest

**Comment by hilburn** [comment]
Also, cute cat

**Comment by hilburn** [comment]
Recipes implemented, loops fixed
Gonna do some NEI magic now to get the quantum cable to display right

**Comment by mrammy** [comment]
yay
