### ISSUE TITLE
Crash bug removing jar

### ISSUE THREAD

**Issue by mrammy** [hilburn/AdvancedSystemsManager#76]
http://hastebin.com/irarihixed.1c

Crashed the server while removing a jar (aspect container) that was inside of a container variable used in a for loop. It continued to crash the server on relaunch with the same error until I removed the manager with MCEdit. Additionally it seemed like the container variables didn't empty out but only one of the jars was used as an output a little like what was described in #75 in regards to chargers.

**Comment by hilburn** [comment]
Well - if it was crashing before being able to place things in more than one jar then that's understandable

**Comment by mrammy** [comment]
It's more like it didn't crash before only was placing aspects into one jar. Upon removing the jar the crash occurs.

**Comment by hilburn** [comment]
hmmm i'll look into it, see if @way2muchnoise did anything strange with the aspect commands

**Comment by mrammy** [comment]
I'll replicate it in more detail in a short while on a testing world and give you some more in depth feedback and a world download. As well as an issue report on something I ran into with the RF node.

**Comment by hilburn** [comment]
Great, I want to get a new release out in the next 12 hours so the more bugs you can find now, the better
