### ISSUE TITLE
Mod requires WailaDataProvider?

### ISSUE THREAD

**Issue by bookerthegeek** [hilburn/AdvancedSystemsManager#77]
https://gist.github.com/bookerthegeek/d9c3b8a893269fd99baa

Pack crash's with your mod installed, but with does not.

When added WAILA, it also does not crash.

Any other information needed?

**Comment by hilburn** [comment]
Hrm... well it definitely shouldn't have that dependency - I'll check it out. Though really, why would you play without WAILA? :P

**Comment by hilburn** [comment]
fixed

**Comment by bookerthegeek** [comment]
Lol... True.

Is the update live?

**Comment by hilburn** [comment]
Not yet I'm afraid, there are a couple of things I need to tweak. Hopefully tonight / 12ish hours from now

**Comment by bookerthegeek** [comment]
Thank you good sir as this is the last mod needing updating before updating my pack. :) cherrio

**Comment by hilburn** [comment]
Sorry it's been slightly delayed - I had to teak more than I thought I would and have ended up doing a fairly major rewrite today.

Will hopefully be finished tomorrow/Monday

**Comment by bookerthegeek** [comment]
.... ok :(

We are really looking forward to using this. Once we go live I'd love for you to come check it out on the production server, as my pack is in beta at the moment. Should be up by Thursday at the latest.
