### ISSUE TITLE
Mod-pack permissions

### ISSUE THREAD

**Issue by bookerthegeek** [hilburn/AdvancedSystemsManager#78]
Altho you do not ask that I post a request anywhere receive permission for the inclusion of your mod in my modpack, here is my request.

> I humble request your divine permission to include this amazing mod in my humble collection of mods I dare to call a modpack.
> - BTG

Also, [HERE](https://github.com/MyM-ModpackTeam/B2B/blob/master/Credits.rst) is my mod index along with permissions so you may gauge future compatibility with other mod's.

I look forward to your replies.

**Comment by hilburn** [comment]
You have permission - just be aware that it is still in fairly early days, and updates **may** cause loss of blocks/items/data - though I am of course doing my best to prevent that. That warning is basically the reason it's not on open permission as it is

**Comment by bookerthegeek** [comment]
Thank you good sir. And yeah, I saw it was early in its days, but hey, more users means more people to find bugs. And don't worry, we will filter our bug reports to try and make sure you only get the valid ones. ;)
