### ISSUE TITLE
Crash on Cluster place

### ISSUE THREAD

**Issue by Shotch** [hilburn/AdvancedSystemsManager#8]
Trying to place an empty cluster doesn't place anything, placing a cluster with anything in it causes a crash, consumes the cluster from the inventory, and isn't in the world upon world re-load.

**Comment by hilburn** [comment]
do you have a crash log for that, and details of what was in the cluster - as that didn't happen in testing

**Comment by Zhab80** [comment]
Forge version ? recommended forge version ?

edit: 1295... Well damn. Recommended forge build for 1.7.10 is 1291. But it seems like that is about to change with 1408.

**Comment by hilburn** [comment]
1295+

**Comment by Shotch** [comment]
It didn't produce a crash log, it brought me to the main menu, I combined a normal cable cluster with void container. I was on Forge version 7.10.85.1291, which may be the source of the issue.

**Comment by Zhab80** [comment]
Dev says 1295+. Which is strange considering that it's not available. It's 1291 or 1300.

**Comment by Shotch** [comment]
Just tested on Forge 1408, same thing occurred.

**Comment by Zhab80** [comment]
I'd like to know which one Hilburn is using. I know it can't be 1295 unless he is using an 1.8 build.

**Comment by hilburn** [comment]
1291, my bad

**Comment by hilburn** [comment]
also: http://puu.sh/i0eJ9/db7d419f98.jpg

I don't know what's happening with that crash

**Comment by Shotch** [comment]
http://gfycat.com/MajorForkedAmericancrow

**Comment by hilburn** [comment]
Ok, there has to be a crashlog for that, in minecraft folder crashreports/crash-DATE_TIME-client.txt

**Comment by Shotch** [comment]
There actually isn't, and that perplexes me. The same thing as when I tired to unset a target side for an input or output, it doesn't produce a crash log, it just takes me to the multiplayer menu. I've provided all crash logs associated with the other things that i found.

**Comment by ghost** [comment]
exact same thing happening to me. I did it with a fluid gate and the same thing happens, sends you to the multiplayer menu

**Comment by Shotch** [comment]
Okay, it didn't produce a crash log, but it did spew this into the console, sorry I didn't notice it before, I generally close the console. http://pastebin.com/YVdGTgvh

**Comment by hilburn** [comment]
Ok I figured it out thanks to that log - was a collision between one of my methods and a vanilla one - works fine in dev but when obfuscated it doesn't work - fixed
