### ISSUE TITLE
NE MOGY DVIGAT COMMANDS

### ISSUE THREAD

**Issue by Sermax18** [hilburn/AdvancedSystemsManager#90]

**Comment by Sermax18** [comment]
Can't Move Commands

**Comment by ghost** [comment]
Wow, Okay. That is hugely useless. So What is your problem?

**Comment by ghost** [comment]
Okay, That's better. So does your game freeze. Do you get an error? Are you able to resolve it by closing and reopening the UI? Does it fix after a map restart? Does it fix at all?
